//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentNoteMVC.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_MVCSchoolEntities : DbContext
    {
        public DB_MVCSchoolEntities()
            : base("name=DB_MVCSchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_classes> tbl_classes { get; set; }
        public virtual DbSet<tbl_clubs> tbl_clubs { get; set; }
        public virtual DbSet<tbl_grades> tbl_grades { get; set; }
        public virtual DbSet<tbl_students> tbl_students { get; set; }
    }
}
