//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentNoteMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_students()
        {
            this.tbl_grades = new HashSet<tbl_grades>();
        }
    
        public byte std_id { get; set; }
        public string std_name { get; set; }
        public string std_surname { get; set; }
        public string std_photo { get; set; }
        public Nullable<bool> std_gender { get; set; }
        public Nullable<byte> std_clb_id { get; set; }
    
        public virtual tbl_clubs tbl_clubs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_grades> tbl_grades { get; set; }
    }
}
