//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentNoteMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_clubs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_clubs()
        {
            this.tbl_students = new HashSet<tbl_students>();
        }
    
        public byte clb_id { get; set; }
        public string clb_name { get; set; }
        public Nullable<short> clb_quota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_students> tbl_students { get; set; }
    }
}
